import { useMutation, useQueryClient } from "@tanstack/react-query";
import toast from "react-hot-toast";
import supabase from "../../services/supabase";
import { useNavigate } from "react-router-dom";

const normalizeEmail = (value = "") => value.trim().toLowerCase();

export function useSignup() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const { mutate: signup, isPending } = useMutation({
    mutationFn: async ({ email, password, firstName, lastName, role, birthYear, parentEmail }) => {
      try {
        const normalizedEmail = normalizeEmail(email);
        const normalizedFirstName = firstName?.trim() || "";
        const normalizedLastName = lastName?.trim() || "";

        // Sign out any existing session to ensure clean signup state
        // This prevents issues where a previous user's session interferes
        try {
          await supabase.auth.signOut();
        } catch {
          // Ignore signout errors - continue with signup
        }

        // Create the auth user first
        const { data: authData, error: authError } = await supabase.auth.signUp(
          {
            email: normalizedEmail,
            password,
            options: {
              emailRedirectTo: `${window.location.origin}/`,
              data: {
                full_name:
                  `${normalizedFirstName} ${normalizedLastName}`.trim(),
                first_name: normalizedFirstName,
                last_name: normalizedLastName,
                role: role,
              },
            },
          }
        );

        if (authError) {
          if (
            authError.message?.toLowerCase().includes("already exists") ||
            authError.message?.toLowerCase().includes("already registered") ||
            authError.status === 400
          ) {
            throw new Error(
              "An account with this email already exists. Please log in instead."
            );
          }
          throw new Error(authError.message);
        }

        if (!authData?.user) {
          throw new Error("Signup failed. Please try again.");
        }

        const userId = authData.user.id;

        // Create the appropriate profile record based on role
        if (role === "teacher") {
          const { error: teacherError } = await supabase
            .from("teachers")
            .upsert(
              [
                {
                  id: userId,
                  first_name: normalizedFirstName,
                  last_name: normalizedLastName,
                  email: normalizedEmail,
                  is_active: true,
                },
              ],
              {
                onConflict: "id",
              }
            );

          if (teacherError) {
            // Don't throw here - let the user complete signup even if profile creation fails
            // The profile can be created later when they try to access teacher features
          }
        } else {
          // Create student record - use upsert to handle potential duplicates
          // All new accounts are always created as active (D-13)
          const { error: studentError } = await supabase
            .from("students")
            .upsert(
              [
                {
                  id: userId,
                  first_name: normalizedFirstName,
                  last_name: normalizedLastName || "",
                  email: normalizedEmail,
                  username: `${normalizedFirstName.toLowerCase() || "student"}${Math.random()
                    .toString(36)
                    .substr(2, 4)}`,
                  level: "Beginner",
                  studying_year: "1st Year",
                  // Store birth year as January 1st (D-10: year-only convention)
                  date_of_birth: birthYear ? `${birthYear}-01-01` : null,
                  parent_email: parentEmail || null,
                  account_status: 'active',
                  // musical_nickname will be generated by DB trigger if configured
                },
              ],
              {
                onConflict: "id",
              }
            );

          if (studentError) {
            // Don't throw here - let the user complete signup even if profile creation fails
            // The profile can be created later when they try to access student features
            console.warn("Student record creation warning:", studentError);
          }

          // Try to promote any placeholder student rows that used this email
          try {
            await supabase.rpc("promote_placeholder_student", {
              p_student_id: userId,
              p_student_email: normalizedEmail,
            });
          } catch (promotionError) {
            console.warn(
              "Placeholder promotion skipped (student signup):",
              promotionError
            );
          }
        }

        return { ...authData, parentEmail };
      } catch (error) {
        console.error("Signup error:", error);
        throw error;
      }
    },
    onSuccess: (data, variables) => {
      const { role } = variables;
      queryClient.invalidateQueries({ queryKey: ["user"] });
      toast.success(
        `${role === "teacher" ? "Teacher" : "Student"} account created successfully!`
      );
      navigate("/");
    },
    onError: (error) => {
      toast.error(error.message);
    },
  });

  return { signup, isPending };
}
