import { useMutation } from "@tanstack/react-query";
import toast from "react-hot-toast";
import supabase from "../../services/supabase";
import { useNavigate } from "react-router-dom";
import { sendParentalConsentEmail } from "../../services/consentService";

const normalizeEmail = (value = "") => value.trim().toLowerCase();

/**
 * Calculate if a date of birth indicates under 13 years old
 * @param {Date} dateOfBirth - The date of birth
 * @returns {boolean} True if under 13
 */
function calculateIsUnder13(dateOfBirth) {
  if (!dateOfBirth) return false;
  const today = new Date();
  const thirteenYearsAgo = new Date(
    today.getFullYear() - 13,
    today.getMonth(),
    today.getDate()
  );
  return dateOfBirth > thirteenYearsAgo;
}

export function useSignup() {
  const navigate = useNavigate();

  const { mutate: signup, isPending } = useMutation({
    mutationFn: async ({ email, password, firstName, lastName, role, dateOfBirth, parentEmail }) => {
      try {
        const normalizedEmail = normalizeEmail(email);
        const normalizedFirstName = firstName?.trim() || "";
        const normalizedLastName = lastName?.trim() || "";

        // Calculate is_under_13 on client (defense in depth - DB has computed column too)
        const isUnder13 = calculateIsUnder13(dateOfBirth);

        // Create the auth user first
        const { data: authData, error: authError } = await supabase.auth.signUp(
          {
            email: normalizedEmail,
            password,
            options: {
              emailRedirectTo: `${window.location.origin}/`,
              data: {
                full_name:
                  `${normalizedFirstName} ${normalizedLastName}`.trim(),
                first_name: normalizedFirstName,
                last_name: normalizedLastName,
                role: role,
              },
            },
          }
        );

        if (authError) {
          if (
            authError.message?.toLowerCase().includes("already exists") ||
            authError.message?.toLowerCase().includes("already registered") ||
            authError.status === 400
          ) {
            throw new Error(
              "An account with this email already exists. Please log in instead."
            );
          }
          throw new Error(authError.message);
        }

        if (!authData?.user) {
          throw new Error("Signup failed. Please try again.");
        }

        const userId = authData.user.id;

        // Create the appropriate profile record based on role
        if (role === "teacher") {
          const { error: teacherError } = await supabase
            .from("teachers")
            .upsert(
              [
                {
                  id: userId,
                  first_name: normalizedFirstName,
                  last_name: normalizedLastName,
                  email: normalizedEmail,
                  is_active: true,
                },
              ],
              {
                onConflict: "id",
              }
            );

          if (teacherError) {
            // Don't throw here - let the user complete signup even if profile creation fails
            // The profile can be created later when they try to access teacher features
          }
        } else {
          // Create student record - use upsert to handle potential duplicates
          // For under-13 users, set account_status to 'suspended_consent'
          const { error: studentError } = await supabase
            .from("students")
            .upsert(
              [
                {
                  id: userId,
                  first_name: normalizedFirstName,
                  last_name: normalizedLastName || "",
                  email: normalizedEmail,
                  username: `${normalizedFirstName.toLowerCase() || "student"}${Math.random()
                    .toString(36)
                    .substr(2, 4)}`,
                  level: "Beginner",
                  studying_year: "1st Year",
                  // COPPA fields
                  date_of_birth: dateOfBirth ? dateOfBirth.toISOString().split('T')[0] : null,
                  parent_email: parentEmail || null,
                  account_status: isUnder13 ? 'suspended_consent' : 'active',
                  // musical_nickname will be generated by DB trigger if configured
                },
              ],
              {
                onConflict: "id",
              }
            );

          if (studentError) {
            // Don't throw here - let the user complete signup even if profile creation fails
            // The profile can be created later when they try to access student features
            console.warn("Student record creation warning:", studentError);
          }

          // Try to promote any placeholder student rows that used this email
          try {
            await supabase.rpc("promote_placeholder_student", {
              p_student_id: userId,
              p_student_email: normalizedEmail,
            });
          } catch (promotionError) {
            console.warn(
              "Placeholder promotion skipped (student signup):",
              promotionError
            );
          }

          // Send consent email for under-13 users
          if (isUnder13 && parentEmail) {
            try {
              await sendParentalConsentEmail(userId, parentEmail);
            } catch (consentError) {
              // Don't fail signup - account created, consent email can be resent
              console.warn("Failed to send consent email:", consentError);
            }
          }
        }

        return { ...authData, isUnder13, parentEmail };
      } catch (error) {
        console.error("Signup error:", error);
        throw error;
      }
    },
    onSuccess: (data, variables) => {
      const { role, dateOfBirth, parentEmail } = variables;
      const isUnder13 = calculateIsUnder13(dateOfBirth);

      if (isUnder13 && parentEmail) {
        // Mask parent email for privacy: "jo***@example.com"
        const maskedEmail = parentEmail.replace(/(.{2}).*@/, '$1***@');
        toast.success(
          `Account created! We've sent an email to ${maskedEmail} for approval.`
        );
      } else {
        toast.success(
          `${role === "teacher" ? "Teacher" : "Student"} account created successfully! Please check your email to confirm your account.`
        );
      }
      navigate("/");
    },
    onError: (error) => {
      toast.error(error.message);
    },
  });

  return { signup, isPending };
}
